### ISSUE TITLE
ability to add groups

### ISSUE THREAD

**Issue by dan1916** [ebaauw/homebridge-sc#11]
Hello,

Would it be possible for you to add an option to assign a group name to the shades from this plugin and then expose a shade accessory to control that whole group at once? Also, can you add 4 generic accessories per group : 
1. one switch that says if any shade from that group is open
2. one to say if any shade from that group is close
3. one switch to say if all shades from that group is close
4. one to say if all shades from that group is open

**Comment by ebaauw** [comment]
No, the SOMA Connect doesn’t support groups and HomeKit accessories (incl. Homebridge) don’t know about HomeKit groups.
