### ISSUE TITLE
Can this plugin cache accessories ?

### ISSUE THREAD

**Issue by dan1916** [ebaauw/homebridge-sc#13]
Hello

I have been using this plugin to manage my 10+ SOMA SHADES S2 blinds from Homekit. It all works great overall. I just have one request to make that I think can avoid a few headaches I am having with this.

Sometimes, the soma connect, running on RPI, connected via Ethernet, randomly fails to either discover a device or shows "unknown" "unknown" in the type and gen fields of the device when /list_devices is called. Most of the time it works, but sometimes, it just fails. A reboot of the pi solves this issue. However, as soon as this plugin discovers the unknown values, it simply removes the accessory. And this is causing havoc on the Homekit side where I have used the accessory in many scenes and automations. Homekit removes it from all the scenes automatically,  and also from the automations and makes them invalid.

This is a big pain. Even after the reboot, the accessory comes back, but it would be treated as a newly added accessory (assigned to the Default room) and still not added to the scenes/automations it was originally part of.

I think this can be avoided by simply showing "No Response" to those accessories which were originally present (even once) and then later becomes unavailable. I don't see how removing the accessory would help in any scenarios. Either a No Response or cached accessory (I have seen some plugins do that, I don't know how), should be helpful. It will not remove the accessory from Homekit side and a simple reboot of the soma connect RPI would fix the issue.

Any thoughts?

**Comment by ebaauw** [comment]
Homebridge SC does cache accessories.  No response is a different issue, but on startup, the accessories are there, with _Status Fault_ set, until the Soma Connect has been found and queried.  Accessories are deleted only if the Connect no longer reports them, presumably because they have been deleted from the Soma Connect.

I see the same behaviour on some of my other plugins: when the bridge/hub/gateway for whatever reason fails to report previously exposed devices, the plugin removes the corresponding accessories.  While this is want you want when you intentionally deleted the device, it’s not what you want when the bridge/hub/gateway acts erroneously.  The problem is, how to tell the difference.

Could you please list the output of `sc info` and `sc list` when the Connect has lost devices?  Do they come back spontaneously or only after rebooting the Connect?

**Comment by dan1916** [comment]
Sorry I did not check using the sc info and sc list commands, I used the soma api end point /list_devices and it showed  "unknown" "unknown" in the type and gen fields of the device when the shade was not discovered by the soma connect. However, calling /get_shade_state still worked, correctly reporting its position. They do sometimes come back. Other times a reboot of soma connect works.

So looks like the connect is not stable 100% of the time. May be 99% it is, but not 100%. For the 1% of the times that it goes down, it takes down with a big cost of loosing the accessory from the scenes and automations.

**Comment by dan1916** [comment]
Anything we can do on this one? It messed up two of my blinds yet again this week and with that all the blinds related automations stopped working because homebridge removed them as asscesory. Can we have a flag somewhere that says "do not remove temporarily unresponsive blinds unless being asked to remove it explicitly"

**Comment by ebaauw** [comment]
Please provide the info I requested.

**Comment by dan1916** [comment]
Before I know and have a chance to go to my pc and execute those commands, they are back as newly added accessory.

**Comment by dan1916** [comment]
@ebaauw This happened again, this time taking away 4 of my blinds in one shot. I quickly ran the sc info command and also checked in the browser's /list_devices. It does report the blinds there, with its MAC address, but instead of showing "type":"shade","gen":"2S" in their fields, it reports "type":"unknown","gen":"unknown"

I think that is the issue. The shade is fully operational from the SOMA app or the connect's web API even at that time. i.e. I can lower it down. It is just that this plugin removes them as soon as it sees the unknown value. 

I have no idea why the connect reports unknown values. Rebooting the connect solves it, but by that time all the accessories are gone and I have to readd it.

**Comment by ebaauw** [comment]
> It is just that this plugin removes them as soon as it sees the unknown value.

Without restarting Homebridge?!  Does Homebridge SC log any warnings?

**Comment by dan1916** [comment]
Yes without a restart. The logs says 
warning: request 207325: SOMA connect result: error

**Comment by dan1916** [comment]
What happens in here https://github.com/ebaauw/homebridge-sc/blob/2ed35c02fc8b6136b4ebfac3913c059339151893/lib/ScClient.js#L20 when the shade.type and gen is returned 'unknown'.

**Comment by ebaauw** [comment]
I'm sorry, I am completely lost.

> Yes without a restart

Homebridge SC does not delete accessories while running.  As far as I know, the symptoms you describe are technically impossible.

On startup, Homebridge restores any accessories by Homebridge SC from `cachedAccesories`.  Homebridge SC subsequently re-creates the accessory delegates for the SOMA Connect accessories.  The accessory delegates for the shade accessories are re-created from the (first) response of from the SOMA Connect.  After initialisation is (almost) complete, Homebridge SC deletes any (presumably stale) accessories for which no delegate has been created.

> What happens in here

That code only executes during startup, when creating (trying to create) a delegate for a shade accessory.

> warning: request 207325: SOMA connect result: error

This warning indicates that the SOMA connect returned an error on the 207325th request.  The log line before that should list the actual request.  Unless some bug causes Homebridge SC to crash (and you restart Homebridge automatically), this wouldn't cause accessories to be deleted.
