### ISSUE TITLE
Option to disable bridge button

### ISSUE THREAD

**Issue by Marfre888** [ebaauw/homebridge-sc#2]
Hi @ebaauw,

I've been testing this plugin, and I have to say it offers some solid features that aren't offered with the standard soma-connect bridge. Thank you so much for your work on this.

I don't know if your intention is to develop this plug further, but my only ask would be to add a way of disabling the switch button on the bridge. I'm not sure what the intention for this button is, but I've discovered that if a tile is 'not supported', which is what it would change into if the button was disabled, the Home app would hide the tile if placed in the 'Default Room' room.

**Comment by ebaauw** [comment]
That's new, the Home app used to show a _Not Supported_ tile, and disable the _Favourite_ setting.  What iOS version are you on?

While I find this plugin to be more stable and functionally richer than the native HomeKit feature of the SOMA Bridge, I still think it's rather poor.  I've moved my attention to homebridge-soma, which interacts directly with the SOMA Smart Shades and Tilts over Bluetooth Low Energy.  While functionally much richer, I'm still ironing out some stability issues.  I'll leave this plugin around, but I don't expect to do much work on it (other than maintaining the dependencies up to date).

**Comment by Marfre888** [comment]
The disabling of the favourite setting is a bug that has been present ever since ios 14.0. It is very annoying, as I have native Homekit devices that expose unsupported tiles in Homekit, but Apple seems to be reluctant to fix it. The only way I've discovered to get over this hurdle was to run Catalina on an external hard drive.

As I said, 'Not Supported' tiles can be hidden by moving them to the 'Default Room'. You can use an app called _Controller_ to do that. Although it still appears in the favourites on the Home app, unless you disable it as above.

Regarding the homebridge-soma plugin, what was your intention for rewriting what soma has already done? In my case, I'm able run soma-connect bridge on the same Pi as Homebridge. From there if I point this plugin to localhost, it works great, about 0.3s slower to react, but the feature set more than makes up for it. How is homebridge-soma working?

**Comment by ebaauw** [comment]
> The only way I've discovered to get over this hurdle was to run Catalina on an external hard drive.

Or an old iOS version.

> As I said, 'Not Supported' tiles can be hidden by moving them to the 'Default Room'.

You can do the same with button tile.

> what was your intention for rewriting what soma has already done

What do you mean?  I started with Homebridge SOMA to support features that the SOMA bridge doesn't, like the solar panel light level, setting the motor speed, en/disabling on-device schedules, syncing the device clock and daylight saving time for in case you don't use the Smart Shades app.

> How is homebridge-soma working?

By connecting to the devices over Bluetooth.

**Comment by Marfre888** [comment]
> > The only way I've discovered to get over this hurdle was to run Catalina on an external hard drive.
> 
> Or an old iOS version.
> 

Yes, a phone with iOS 13 would also work (not iOS 12), but it is a lot harder to find a phone with the correct firmware in 2021.

> > As I said, 'Not Supported' tiles can be hidden by moving them to the 'Default Room'.
> 
> You can do the same with button tile.


How so? If the button tile is enabled, Homekit will expose it as a button, and if you try to move it to 'Default Room' it will just create an additional room, and not hide it.

 
> > what was your intention for rewriting what soma has already done
> 
> What do you mean? I started with Homebridge SOMA to support features that the SOMA bridge doesn't, like the solar panel light level, setting the motor speed, en/disabling on-device schedules, syncing the device clock and daylight saving time for in case you don't use the Smart Shades app.

Ahh no, I understand that. I meant why not use soma-connect then call the api? Are there any benefits to connecting directly to Bluetooth?

> 
> > How is homebridge-soma working?
> 
> By connecting to the devices over Bluetooth.

I meant is it stable? As with the native soma-connect firmware, I've been running into a lot of weird problems.

**Comment by ebaauw** [comment]
> How so? If the button tile is enabled, Homekit will expose it as a button, and if you try to move it to 'Default Room' it will just create an additional room, and not hide it.

Use a decent HomeKit app.

> Ahh no, I understand that. I meant why not use soma-connect then call the api? Are there any benefits to connecting directly to Bluetooth?

I don’t think you understand.  The devices expose an API over BLE for the full functionality.  This BLE API is used by the Smart Shades app, by the SOMA Connect, and by Homebridge SOMA.  The Connect offers a different API over HTTP, with very limited functionality.  This is used by Homebridge SC.  As the Connect isn’t open source, I cannot extend it to expose the full functionality over the HTTP API.

> I meant is it stable? As with the native soma-connect firmware, I've been running into a lot of weird problems.

The Connect is just a Raspberry Pi OS image running a service that offers, amongst others, the HTTP API and the native HomeKit function.  This service is a bundled NodeJS programme, using Noble for BLE and HAP-NodeJS for HomeKit feature, basically the same technology that Homebridge SOMA uses.  If you check on the SOMA Connect, it crashes quite often, but is restarted automatically.

I’m new to programming for Bluetooth, and not sure what to expect.  Ironing out all “weirdness” is a bit of a challenge and work in progress, see the open issue on Homebridge SOMA.

**Comment by Marfre888** [comment]
> > How so? If the button tile is enabled, Homekit will expose it as a button, and if you try to move it to 'Default Room' it will just create an additional room, and not hide it.
> 
> Use a decent HomeKit app.

Sorry, but that's a pointless argument. I own all the Homekit apps, there is no better Homekit app for presentation than the Home app, and that's a fact.


> > Ahh no, I understand that. I meant why not use soma-connect then call the api? Are there any benefits to connecting directly to Bluetooth?
> 
> I don’t think you understand. The devices expose an API over BLE for the full functionality. This BLE API is used by the Smart Shades app, by the SOMA Connect, and by Homebridge SOMA. The Connect offers a different API over HTTP, with very limited functionality. This is used by Homebridge SC. As the Connect isn’t open source, I cannot extend it to expose the full functionality over the HTTP API.

Ahh okay, so you're targeting the API from the device itself. That makes sense now. There was an update to soma-connect recently that adds light levels to HTTP API.

> > I meant is it stable? As with the native soma-connect firmware, I've been running into a lot of weird problems.
> 
> The Connect is just a Raspberry Pi OS image running a service that offers, amongst others, the HTTP API and the native HomeKit function. This service is a bundled NodeJS programme, using Noble for BLE and HAP-NodeJS for HomeKit feature, basically the same technology that Homebridge SOMA uses. If you check on the SOMA Connect, it crashes quite often, but is restarted automatically.
> 
> I’m new to programming for Bluetooth, and not sure what to expect. Ironing out all “weirdness” is a bit of a challenge and work in progress, see the open issue on Homebridge SOMA.

I'm more wondering if you had to run Homebridge Hue (with Raspibee) and Homebridge Soma, if it would start to cause problems on the Pi. I have several devices running on Homebridge, so don't want to experiment too much as long as everything is running fine.

**Comment by ebaauw** [comment]
> Sorry, but that's a pointless argument. I own all the Homekit apps, there is no better Homekit app for presentation than the Home app, and that's a fact.

Moving the tile to the default room is a one-time action.  After that you can stick to Home.

> I'm more wondering if you had to run Homebridge Hue (with Raspibee) and Homebridge Soma, if it would start to cause problems on the Pi. 

Homebridge Hue and Homebridge SOMA will probably play nicely together.  If not, you can use child bridges.  However, the Zigbee radio and BLE radio share the 2.4 GHz band and are less likely to play nicely.

**Comment by Marfre888** [comment]
Lol 🤣🤣 thanks for your help as always.

Hope you develop a better Homekit app soon!

**Comment by ebaauw** [comment]
Hm, for me, the appeal of developing Homebridge plugins is not having to deal with UI stuff.  A HomeKit app is not even on my list.
