### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by HazardNZ** [ebaauw/homebridge-sc#4]
Hi, I've just installed Homebridge SC and it's all working well for controlling my blinds. However I've noticed that the battery on all of the units says 100%. When I look at the blinds through the Smart Shades app, I get the actual reading of the battery.

When charging, the Charging status updates correctly, it just seems the battery indicator is stuck at 100%.

Just curious if you've encountered this or if there's something I'm missing?

Thanks.3

**Comment by ebaauw** [comment]
What is the battery level reported by the SOMA Connect?  Can you run from the command line:

`sc -H `_host_` battery -S `_shade_

See `sc -h` for help.

Alternatively, please turn on DEBUG mode in Homebridge, capture a log file, and attach that here.  See https://github.com/ebaauw/homebridge-hue/wiki/FAQ#homebridge

**Comment by HazardNZ** [comment]
sorry I've been away for a few days, I'll run this tomorrow and report back.
Thanks
