### ISSUE TITLE
Whitelist feature

### ISSUE THREAD

**Issue by petedavey** [ebaauw/homebridge-sc#5]
Due to how Some-Connect works, it seems to broadcast and connect to all Soma Shades / Tilt products within a general area as long as there is radio contact. Being in a larger home where signals can be too low , you would probably need to install multiple devices running soma-connect. Unfortunately there is no way to tell a soma connect devices which devices to communicate with, so ideally with this plugin if we could have such a function that would be great. So, in addition to providing the IP address of each connect device, also have a whitelist feature where you can pop in the MAC ID as well so that it ignores the low signal units.

**Comment by ebaauw** [comment]
In v1.0.15.
