### ISSUE TITLE
Battery Issue

### ISSUE THREAD

**Issue by dampney** [ebaauw/homebridge-sc#7]
I'm finding the Battery percentage for 1/2 of my Soma blinds in HomeKit is wrong compared to device.

As attached screenshots, HomeKit says 100%, while the offical Soma Smart Shades app is 8%.

![image](https://user-images.githubusercontent.com/59161034/184315945-f6c82b7a-8ab3-4a36-85a1-08a2597b08db.jpeg)

```

{
    "hosts": [
        {
            "host": "xxx.xxx.X.xxx",
            "shades": [
                "Xx....:xx",
                "Xx....:xx"
            ]
        }
    ],
    "name": "Soma",
    "_bridge": {
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 36609
    },
    "platform": "SC"
}

```

**Comment by ebaauw** [comment]
Hiomebridge SC just shows what the SOMA bridge reports.  What does `sc -H ... battery` show?

Make sure to close the blind in the _Smart Blinds_ app, so the SOMA bridge can refresh the blind state.

**Comment by dampney** [comment]
I'm not sure what "sc -H ... battery" means but connecting to the HTTP API, I'm getting the correct battery level.

```
{"result":"success","version":"2.3.1","mac":"xx:xx:xx:xx:xx:xx","battery_level":360,"battery_percentage":0}
```

The battery level is 0 because I've been testing the solar panel window positions. Homekit still shows it's 100%. Even with 40%, its always 100% in Homekit.

**Comment by ebaauw** [comment]
Odd.  Homebridge SC should update the battery level every 2 minutes.  Are the positions and light levels reflected correctly in HomeKit, for the shades that don't show the correct battery level?

`sc` is a command line utility included in Homebridge SC to interact with the SOMA Connect HTTP API.

Could you please turn on DEBUG mode in Homebridge, set _Log Level_ to 2 (in the bridge accessory) and capture and attach the Homebridge log file?  That should log the API calls Homebridge SC makes, and the responses from the Connect.  Every two minutes, you should see a call of `/list_devices`, followed by a `/get_shade_state`, a `/get_battery_level` and a `/get_light_level` for each shade.

**Comment by dxa13** [comment]
Hi Erik,
Thanks for this plugin... I am having the same issue, my two blinds show 100 % battery level all the time (they are/were at 10% and 58% per the Smart Shades app).  Also, at least for one of them the % open indicator is 2% off vs both the smart shades App, and vs. what Soma Connect reports in the home app.  Here is the Homebridge Log file, just for the SC plug-in.

Debug Level was turned ON today after 2pm, all previous log entries don't contain include it, but figured it would not hurt to dump it too.

[homebridge.log.filtered.txt](https://github.com/ebaauw/homebridge-sc/files/9397232/homebridge.log.filtered.txt)

**Comment by ebaauw** [comment]
Thanks.  Homebridge SC seems to work as expected, and the API calls return OK.  It would seem the API returns something Homebridge SC doesn’t fully understand.  Could you please set _Log Level_ to 3 to log the API response body?

> Also, at least for one of them the % open indicator is 2% off vs both the smart shades App, and vs. what Soma Connect reports in the home app.

Homebridge SC rounds the position to the nearest multiple of 5%, as the shades tend to stop near the target position, but not exactly on it, and Home wants to see the current position match the target position exactly, to conclude the shades are no longer moving.

I assume the light level is reflected correctly?

**Comment by dxa13** [comment]
Would you kindly tell me how to set the log level to 3? I don't see a Log Level characteristic in the Eve app for either the Hub or Shade.  I tried adding "logLevel": "3" and "logLevel": "vdebug" in my json config under the child bridge definition for SC; I am not sure I see any more debug output...  I am running homebridge as a service on a RPI.  

[homebridge.log-7.filtered.txt](https://github.com/ebaauw/homebridge-sc/files/9401994/homebridge.log-7.filtered.txt)

**Comment by ebaauw** [comment]
It’s on the accessory for the SOMA Connect.  It should show as a dummy switch.

**Comment by dxa13** [comment]
Thanks, here it is.  Note that:
- I have two blinds, Left Blind HB, Right Blind HB.
- Light sensor readings are good/accurate for both.
- I charged the left blind yesterday, so it is at 100% (as reported by the Soma App and Home app).
- However, I forgot to connect the solar panel back onto the left blind, so light sensor readings are non-existent.
- I see in the new debug messages that the right blind is returning at 56% battery level, which is accurate as per the Soma App. But, the Home App (and Eve) show 100%.

[homebridge.log-8.filtered.txt](https://github.com/ebaauw/homebridge-sc/files/9402169/homebridge.log-8.filtered.txt)

**Comment by ebaauw** [comment]
> I see in the new debug messages that the right blind is returning at 56% battery level, which is accurate as per the Soma App. But, the Home App (and Eve) show 100%.

I think I've found a bug, causing the _Battery Level_ not to be updated and always show default 100%.  Unfortunately, I don't have any SOMA device nor Connect ready to test.  Could you please try beta v1.0.17-0 and see if that shows the correct battery percentage?

> I'm finding the Battery percentage for 1/2 of my Soma blinds in HomeKit is wrong compared to device.

That would be the half of the blinds that happen to have a battery percentage of 100?

> However, I forgot to connect the solar panel back onto the left blind, so light sensor readings are non-existent.

What do you mean "non-existent"?  The SOMA Connect returns `light_level` 0, just like when the solar panel is connected, but not getting any light.  Similarly, when USB power is connected instead of the solar panel, `light_level` returns something in the 600 range (if memory serves), which is indistinguishable from the solar panel working at full swing.

**Comment by dxa13** [comment]
Hi Erik, 

Done. And the beta version now reports the correct battery level for both blinds, left at 100% (charged yesterday), right at 52%.  Thank you very much for the fix! 

Regarding you other responses: 

> > I'm finding the Battery percentage for 1/2 of my Soma blinds in HomeKit is wrong compared to device.

This was posted by the ticket originator, not me, hence I cannot comment on the matter.

> > However, I forgot to connect the solar panel back onto the left blind, so light sensor readings are non-existent.
> 
> What do you mean "non-existent"? The SOMA Connect returns `light_level` 0, just like when the solar panel is connected, but not getting any light. Similarly, when USB power is connected instead of the solar panel, `light_level` returns something in the 600 range (if memory serves), which is indistinguishable from the solar panel working at full swing.

I just meant that the Home app was reporting 0.0003 lux (i.e. 0) for the one motor not connected to either the AC power adapter or the solar panel, which as you pointed out is normal.

**Comment by ebaauw** [comment]
In v1.0.17.
