### ISSUE TITLE
Battery Drain & Light Level

### ISSUE THREAD

**Issue by bkconrad1** [ebaauw/homebridge-sc#8]
I recently started using homebridge-sc and overall I am impressed. Two items that I would like to make you aware of. 

- First, I only use the solar panel on 2 of my 7 soma shade devices. Would it be possible to enhance the configuration to disable collection of ambient light on the devices that I am not using the solar panel with. 
- Second, the batteries on the soma connects are draining much faster than before(using native soma HomeKit integration). Is there a way to reduce the polling frequency to improve battery life?

**Comment by ebaauw** [comment]
Ad first:  Afaik the SOMA Connect doesn’t report whether a solar panel is connected to SOMA Smart Shade or Tilt, so it would have to be an additional config.json setting, which would overly complicate the structure.

Ad second: Do you have battery-powered SOMA Connect servers?  You can adjust the polling rate for the position through _Heartrate_ on the Connect accessory.  You need a decent HomeKit app for that, as Apple’s Home doesn’t support custom characteristics.  Note that this won’t change the interaction between the Connect and the Smart Shades or Tilts, as these report the position through the BLE advertisement.  Homebridge SC polls the light level and battery every two minutes.  I’m not sure, but I think the Connect keeps a cached copy of the device state, so changing the rate at which Homebridge SC polls the Connect wouldn’t change the rate at which the Connect polls the devices.

**Comment by bkconrad1** [comment]
The SOMA connects are plugged in and using wired connections. 


I modified the polling rate in your code from two minutes to 10 minutes and the batter drain problem went away. I am going to slowly lower it to see if/when it the drain returns. I will let you know the outcome

**Comment by ebaauw** [comment]
Any update?

**Comment by bkconrad1** [comment]
I just lowered the timer from 10 minutes to 5 minutes. I will update you in a week

**Comment by bkconrad1** [comment]
setting the polling interval to 5 minutes results in no incremental battery drain.
